#ifndef INPUTMODE_H
#define INPUTMODE_H

enum class InputMode
{
    HELP,
    TITLE_SCREEN,
    CHARACTER_CREATION,
    GAME,
    YES_NO_CHOICE,
    MULTI_CHOICE,
    QUIZ,
    ESCAPE_CHECK,
    SAVE_CONFIRMATION,
    LOAD_CONFIRMATION,
    SAVEDEL_CONFIRMATION,
    KEY_DEATH,
    KEY_GAME_START,
    KEY_GAME_OVER,
    KEY_REDIRECT
};

#endif // INPUTMODE_H
